### PR TITLE
Add releases folder with Terra 0.6 and 0.7 release guides.

### PR DESCRIPTION
**Pull request by dongreenberg**
Introduces a "releases" folder for notebook guides to major Qiskit releases, including guides for Terra 0.7 and 0.6 (Ali agreed this made sense). I am working on the guide for Aqua 0.4 presently.

(Third time's a charm 😁)

### CODE REVIEW

**Comment by jaygambetta** [comment]
you need to rerun and you have some errors. I see hex counts as well.

**Comment by jaygambetta** [comment]
Also now we have updated to master please push there

**Comment by mtreinish** [comment]
sigh, I apologize for that. Github clearly did the wrong thing when I adjusted the base from the terra branch to master. It looks like it's trying to remerge the old state of master from when things branched. I have no idea how github could screw up a simple rebase. I'll fix this locally and force push

**Comment by mtreinish** [comment]
OK, I've manually rebased this onto master (the issue was that terra0_7 and master don't rebase cleanly anymore so there are unresolvable merge conflicts elsewhere in the history unrelated to this patch) so I just bypassed that and targeted the commit on master for you. @dongreenberg you will still need to rerun it though per @jaygambetta review earlier. I only fixed the git side of things.

**Comment by attp** [comment]
`from qiskit.transpiler.passes import BasicMapper, CXCancellation, LookaheadMapper`
causes an error: `ImportError: cannot import name 'BasicMapper' from 'qiskit.transpiler.passes'`

**Comment by dongreenberg** [comment]
- Notebook corrected and runs.
- The hex is WAI, part of demonstrating to users why they should not use results.data().

**Comment by jaygambetta** [comment]
Can you switch this from mapper to StochasticSwap

**Comment by jaygambetta** [comment]
Also, there is still not anything about the backend updates.

**Comment by jaygambetta** [comment]
I also see that you have LegacySimulators this should Aer

**Comment by jaygambetta** [comment]
Can you also make the location just releases not qiskit/resleases
